image:
  repository: "asia-south1-docker.pkg.dev/kong-gke-493913/kong-repo/kong-custom"
  tag: "3.9-amd64"
  pullPolicy: Always

env:
  role: "data_plane"
  database: "off"

  cluster_mtls: "pki"
  cluster_control_plane: "00156f2e1e.in.cp.konghq.com:443"
  cluster_telemetry_endpoint: "00156f2e1e.in.tp.konghq.com:443"

  cluster_cert: "/etc/secrets/konnect-client-tls/tls.crt"
  cluster_cert_key: "/etc/secrets/konnect-client-tls/tls.key"

  lua_ssl_trusted_certificate: "system"
  tls_certificate_verify: "off"

secretVolumes:
  - konnect-client-tls

proxy:
  enabled: true
  type: LoadBalancer

manager:
  enabled: false

ingressController:
  enabled: false  
